const legacyData = [
    {
        "Name": "Khan Zaid Shafique",
        "Batch / Graduation Year": "2023.0",
        "Branch": "MME",
        "Can we mention your name when this is shared with juniors?": "Yes",
        "What is ONE thing you want to pass on to the juniors?": "Build Character that last longer than your career",
        "What is one of your favourite memories from VNIT?": "https://drive.google.com/open?id=1L030nsupkraMWluH5dWjUNvs41jXnpI9",
        "Was there a person, event, club, place or experience that made your college life special?": "Brothers from Friday",
        "What is something at VNIT that you think juniors should experience at least once?": "Failures",
        "What is something you wish you had taken more seriously?": "Finding a niche",
        "What is something you wish you had worried less about?": "Placements",
        "What is one decision you are really grateful you made during college?": "Actively Involving with Hood",
        "If you could go back to your first year, what would you do differently?": "Nothing",
        "What is something you learned about internships, placements, projects or careers that you wish you knew earlier?": "Choosing a career to pursue is much more important than just getting placed anywhere.",
        "What is one resource that genuinely helped you?": "Allah and its people",
        "Is there an internship, interview, project or experience you think future batches would benefit from knowing about?": "Choose anything and go deep in it",
        "Any experience with any particular batch/senior that can resonate with upcoming batches.": "Explore different sectors while being in college by connecting with your seniors.",
        "What is one thing VNIT taught you that had nothing to do with academics?": "Time Management",
        "What is one thing you learned about friendships, people, failure, confidence, money or life?": "Life goes on, money loves to flow, confidence is the key, failure builds character, people come and go, if you are benefiting from a friendship without losing anything then it is not real",
        "What is one habit that genuinely changed you?": "Asking questions and thriving for answers",
        "What is something you understand today that you didn\u2019t understand when you entered VNIT?": "Connection matters",
        "Is there a book, person, quote, lecture, experience or idea that influenced you deeply?": "Embarrassment is a very little explored emotion.",
        "To the VNIT student reading this five years from now\u2026": "Behave like you are representative of a marginalised community.",
        "If juniors remember only ONE thing from you, what should it be?": "Do not remember me.",
        "Is there anything else you want to leave?": "Here is my number : +971 56 682 0887",
        "Would you be open to helping juniors in the future?": "Yes",
        "What could juniors reach out to you about?": "Operations, Finance & Islamic affairs",
        "LinkedIn / Email": "zaidkhanfr30@gmail.com",
        "Current country and company": "MBAL Investments, UAE"
    },
    {
        "Name": "M.Shozib Bilal",
        "Batch / Graduation Year": "2026.0",
        "Branch": "Mechanical",
        "Can we mention your name when this is shared with juniors?": "Yes",
        "What is ONE thing you want to pass on to the juniors?": "The most important thing when u passout from the college is having a good job and to take it u required a good academic background the most important is CGPA this is the first step to get a higher package or good placement so I request all of u no clubs no friends no gfs nothing will come with u except a good job so try to be more selective while applying for any company if ur interested in that field then u should but don't think I want only job koi bhi chalega not like this. And try to take a package of atleast 10lpa+ if u can because later u regret why I choose this company and don't be panic and be selective while applying for company don't apply randomly see it's location company brand the works align with ur passion or not and the most important is CTC. more CTC more in hand salary.",
        "Was there a person, event, club, place or experience that made your college life special?": "Nothing",
        "What is something at VNIT that you think juniors should experience at least once?": "My point of view is that nothing matters a lot if ur good in academic ultimately we are in college not in industry but if u can maintain all the things so u  should experience whatever u want no limitation",
        "Would you be open to helping juniors in the future?": "Yes",
        "Current country and company": "India Sunflag Steel company"
    },
    {
        "Name": "Syed Mukhtadir",
        "Batch / Graduation Year": "2026.0",
        "Branch": "Civil",
        "Can we mention your name when this is shared with juniors?": "Yes",
        "What is ONE thing you want to pass on to the juniors?": "Enjoy your college life and establish prayer",
        "What is one of your favourite memories from VNIT?": "https://drive.google.com/open?id=1i1NR-ezjqD6ctauFewU6LW9lSJbtEL1h",
        "Was there a person, event, club, place or experience that made your college life special?": "Friday Group",
        "What is something you wish you had taken more seriously?": "Free time",
        "What is something you wish you had worried less about?": "Attendance",
        "What is one decision you are really grateful you made during college?": "Internship",
        "If you could go back to your first year, what would you do differently?": "Just short cuts in filling journals",
        "What is something you learned about internships, placements, projects or careers that you wish you knew earlier?": "About different Scopes / Fields for Engineers",
        "What is one resource that genuinely helped you?": "Seniors",
        "Is there an internship, interview, project or experience you think future batches would benefit from knowing about?": "NHAI Semester Long Intership",
        "Is there anything you would like future batches to continue or preserve?  An event, tradition, resource, club activity, community initiative, value, or anything else you don\u2019t want to disappear.": "https://drive.google.com/open?id=1Cnp8FMBH81BtLvDc6hip-fboe1_FZHYa",
        "Any experience with any particular batch/senior that can resonate with upcoming batches.": "With Luqman Bhai",
        "What is one thing you learned about friendships, people, failure, confidence, money or life?": "Always Choose your own path",
        "Would you be open to helping juniors in the future?": "Yes",
        "What could juniors reach out to you about?": "Anything",
        "Current country and company": "INDIA, VCONSTRUCT"
    },
    {
        "Name": "Sayyed Kaizad",
        "Batch / Graduation Year": "2024.0",
        "Branch": "Chemical engineering",
        "Can we mention your name when this is shared with juniors?": "Yes",
        "What is ONE thing you want to pass on to the juniors?": "1) Cgpa matters a lot. \n2) Try to become a tnp secretary.",
        "What is something you wish you had taken more seriously?": "Learn to swim, play atleast one sport seriously.",
        "LinkedIn / Email": "https://www.linkedin.com/in/kaizad-sayyed-057056218?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
        "Current country and company": "Microland, Bengaluru, India"
    },
    {
        "Name": "Muhammad Ayaan Shaikh",
        "Batch / Graduation Year": "2026.0",
        "Branch": "CSE",
        "Can we mention your name when this is shared with juniors?": "Yes",
        "What is ONE thing you want to pass on to the juniors?": "Make as much memories possible",
        "Current country and company": "India"
    },
    {
        "Name": "Haidar Hasan",
        "Batch / Graduation Year": "2021.0",
        "Branch": "Mechanical",
        "Can we mention your name when this is shared with juniors?": "Yes",
        "What is ONE thing you want to pass on to the juniors?": "Give your best in everything you do, and then leave the rest to Allah",
        "What is one of your favourite memories from VNIT?": "https://drive.google.com/open?id=1QBtgAh3KfCM7z6tz5ky2SW5WM8UK0NE9",
        "Was there a person, event, club, place or experience that made your college life special?": "My just senior batch members from Hood group (currently Friday group)",
        "What is something at VNIT that you think juniors should experience at least once?": "Explore the co curricular opportunities as well",
        "What is something you wish you had taken more seriously?": "Soft skills",
        "What is something you wish you had worried less about?": "Pointers offcourse",
        "Would you be open to helping juniors in the future?": "Yes",
        "LinkedIn / Email": "https://www.linkedin.com/in/haidar-hasan-387734171",
        "Current country and company": "Evonith Steel, India"
    },
    {
        "Name": "Amaan Siddique",
        "Batch / Graduation Year": "2.0",
        "Branch": "Civil engineering",
        "Can we mention your name when this is shared with juniors?": "Yes",
        "What is ONE thing you want to pass on to the juniors?": "Shamelessly promote your work. The best portfolio doesn't wins , the one that is visible wins.",
        "What is something at VNIT that you think juniors should experience at least once?": "Playing outdoor sports together",
        "What is something you wish you had taken more seriously?": "First semester academics",
        "What is something you wish you had worried less about?": "I should have worried less about perfection",
        "What is one decision you are really grateful you made during college?": "Creating an online presence/ content creation",
        "If you could go back to your first year, what would you do differently?": "I would start content creation from the first year and will give bit more attention to  academics",
        "What is one resource that genuinely helped you?": "Our own Friday group",
        "What is one thing VNIT taught you that had nothing to do with academics?": "Be extrovert, don't be afraid from approaching strangers",
        "What is one thing you learned about friendships, people, failure, confidence, money or life?": "You don't get confidence at start you get it as u continue with ur work",
        "What is one habit that genuinely changed you?": "Diet and physical activity as I was unfit earlier these two things helped me to transform myself and get in better physique than ever before",
        "What is something you understand today that you didn\u2019t understand when you entered VNIT?": "CGPA does matter",
        "Is there a book, person, quote, lecture, experience or idea that influenced you deeply?": "Not everything needs to stay just because it was written first",
        "To the VNIT student reading this five years from now\u2026": "people can't appreciate...what they don't understand.\nYou might have the best ideas...the right intentions...or even the right answers.\nBut if you can't put them into words...\npeople may never see what you actually have to offer.\nSo Just work on being better at communicating.",
        "If juniors remember only ONE thing from you, what should it be?": "Shamelessly promote your own work",
        "Is there anything else you want to leave?": "Work on building a visible portfolio rather than a perfect one",
        "Would you be open to helping juniors in the future?": "Yes",
        "What could juniors reach out to you about?": "If they want to create something online",
        "LinkedIn / Email": "amaansiddique574@gmail.com",
        "Current country and company": "India"
    },
    {
        "Name": "Syed Mohammad Asim",
        "Batch / Graduation Year": "2021.0",
        "Branch": "Architecture",
        "Can we mention your name when this is shared with juniors?": "Yes",
        "What is ONE thing you want to pass on to the juniors?": "Rizq is written, don't fret too much over it. Prioritise things that matter most, religion, then survival, then health, then family, then career, then passion/hobbies/friends, etc.",
        "Was there a person, event, club, place or experience that made your college life special?": "Ali bhai, Zeeshan Bhai are still two massive pillars for me. Keeping in touch, encouraging, supporting. They were massive help during bachelor's. Also Dr. Ameen (Al khair) has always been like a big brother. We used to pray together. Be like these people for your juniors. Everything else, we forget.",
        "What is something at VNIT that you think juniors should experience at least once?": "Travel far, travel long. Experience the lives of the less fortunate first hand.",
        "What is something you wish you had taken more seriously?": "Mental health. Excessive of work/time pass/workout/anything is not healthy. Nobody teaches Emotional intelligence, we have to read, learn and practise ourselves. Start early.",
        "What is something you wish you had worried less about?": "Money",
        "What is one decision you are really grateful you made during college?": "Every time I decided to pray with my brothers. Nothing else matters.",
        "If you could go back to your first year, what would you do differently?": "I would be calm, slow, intentional with my every action and thought. Not hyper.",
        "What is something you learned about internships, placements, projects or careers that you wish you knew earlier?": "Nobody here is it there trying to think what is best for us. Everybody is looking out for their own interest, that is completely fine. Some people are kind though, but when you are in survival mode, assume the worst to stay safe. When you are comfortable, have cushion, then you can have the luxury to think that most people are good and nice, etc.",
        "What is one resource that genuinely helped you?": "Do a proper course in islamic studies. That becomes an anchor for you for life.",
        "Is there an internship, interview, project or experience you think future batches would benefit from knowing about?": "Architecture: pay is horrible, start your own thing ASAP. If not possible due to financial needs, then go into high paying sub-stream, like BIM, etc. Stay in halal work. Time and hard work are NOT directly proportional to money. Rizq is written, just follow the priority list, work average, take informed decisions, pray. You'll always get exactly what was written no matter what you do.",
        "Any experience with any particular batch/senior that can resonate with upcoming batches.": "Ali bhai took care of all of us, spent crazy amount of time and energy to individually talk to even super juniors. Extremely inspirational.",
        "What is one thing VNIT taught you that had nothing to do with academics?": "Life is very tough for most people, most things are circumstantial.",
        "What is one thing you learned about friendships, people, failure, confidence, money or life?": "Refer above",
        "What is one habit that genuinely changed you?": "Relaxing instead of over thinking when things go south. Still not mattered it, but when successful, things are smooth.",
        "What is something you understand today that you didn\u2019t understand when you entered VNIT?": "The massive range of different walks of life people come from. Unfathomable.",
        "Is there a book, person, quote, lecture, experience or idea that influenced you deeply?": "I would talk about all my teenage issues with Ameen bhai, Ali bhai, so they definitely shaped me a lot.",
        "To the VNIT student reading this five years from now\u2026": "Take stuff seriously, but not too seriously. Balance between all different aspects of life. Don't follow the hustle culture, most of the common western ideologies. Always be critical of whatever you read/come across even if it is coming from a big figure that seemingly everybody revers.",
        "If juniors remember only ONE thing from you, what should it be?": "Workout!!!",
        "Is there anything else you want to leave?": "Yeah, all my bad habits haha. No, I think I have covered everything.",
        "Would you be open to helping juniors in the future?": "Yes",
        "What could juniors reach out to you about?": "Anything, really, life, money, career, mental health, marriage, children, architecture",
        "LinkedIn / Email": "www.linkedin.in/asim1000\nsyedasim9816@gmail.com",
        "Current country and company": "India, ArchiCodes (Owner)"
    },
    {
        "Name": "Abdul Muqsit Abrar",
        "Batch / Graduation Year": "2024.0",
        "Branch": "Chemical",
        "Can we mention your name when this is shared with juniors?": "Yes",
        "What is ONE thing you want to pass on to the juniors?": "It is highly advisable to maintain a CGPA above 7.5. We recommend pursuing Master's degrees from institutions in the UK, US, or other international locations. Should your CGPA be lower in your final years and you receive a job offer, it is prudent to accept it irrespective of the initial compensation package. The current external market conditions are increasingly challenging, and significant salary increases can often be achieved within a relatively short timeframe.",
        "What is one of your favourite memories from VNIT?": "https://drive.google.com/open?id=1Te_RBBxiVOSRjqMMIXPVjKbcVHJVLZ9l",
        "Was there a person, event, club, place or experience that made your college life special?": "Do join Brother's Day out.",
        "What is something at VNIT that you think juniors should experience at least once?": "Student Council",
        "What is something you wish you had taken more seriously?": "My CGPA",
        "What is something you wish you had worried less about?": "Making Friends",
        "What is one decision you are really grateful you made during college?": "Keep in touch with seniors & alumni.",
        "If you could go back to your first year, what would you do differently?": "Focus on building core skills & improve communication skills",
        "What is something you learned about internships, placements, projects or careers that you wish you knew earlier?": "In today's world, internship plays a good role in finding jobs.",
        "What is one resource that genuinely helped you?": "Alumni Network",
        "Is there an internship, interview, project or experience you think future batches would benefit from knowing about?": "NA",
        "Is there anything you would like future batches to continue or preserve?  An event, tradition, resource, club activity, community initiative, value, or anything else you don\u2019t want to disappear.": "https://drive.google.com/open?id=1ijHajEOuVip9lyZDTauEltNVU_5GHzKl",
        "What is one thing VNIT taught you that had nothing to do with academics?": "Leadership.",
        "What is one thing you learned about friendships, people, failure, confidence, money or life?": "One thing VNIT taught me is that people and friendships change with time, and that\u2019s okay.\n\nWhen I joined college, I thought the people I started with would always remain the closest to me. But over the years, I realised that some people leave, some relationships become distant, and a few unexpectedly become lifelong friends. College also taught me that failure doesn\u2019t mean you\u2019re incapable\u2014it simply shows you where you need to improve.\n\nSo, if I had to take one lesson from my VNIT life, it would be: don\u2019t chase people, don\u2019t be afraid of failure, and don\u2019t compare your journey with someone else\u2019s. Keep growing, and the right people and opportunities will find their place in your life.",
        "What is one habit that genuinely changed you?": "Consistency",
        "What is something you understand today that you didn\u2019t understand when you entered VNIT?": "When I entered VNIT, I thought that getting good grades, building a strong CV, and having everything figured out were the most important things. Today, I understand that college is much more about figuring out who you are, learning how to deal with uncertainty, and building relationships with people.\n\nI also understand that everyone is on a different timeline. Someone getting placed before you or doing better academically doesn't mean you're falling behind. Your career is a long journey, and college is just one chapter of it.",
        "Is there a book, person, quote, lecture, experience or idea that influenced you deeply?": "Ther is a saying in urdu \" kaon seekha hai sirf kitabo se, har kisiko ek hadsa zaroori hai\" so you will learn with time.",
        "If juniors remember only ONE thing from you, what should it be?": "My Helping nature.",
        "Would you be open to helping juniors in the future?": "Yes",
        "What could juniors reach out to you about?": "Anything.",
        "LinkedIn / Email": "abrar221@gmail.com",
        "Current country and company": "INDIA, PHYSICS WALLAH"
    },
    {
        "Name": "Mateen Mohsin",
        "Batch / Graduation Year": "2019.0",
        "Branch": "Mechanical Engineering",
        "Can we mention your name when this is shared with juniors?": "Yes",
        "What is ONE thing you want to pass on to the juniors?": "Balance academics and college life optimally. Try to remain calm always !. Don't react too much to any negative experience, it's always temporary and won't matter much as time passes, But do learn from it !",
        "Was there a person, event, club, place or experience that made your college life special?": "A few seniors like Ali Sahibzada, Azeem, Jawad, Musadiq and many others and of course my batchmates too !",
        "What is something you wish you had taken more seriously?": "My academics and CGPA :(",
        "What is something you wish you had worried less about?": "Failing",
        "If you could go back to your first year, what would you do differently?": "Take lectures seriously. Make detailed notes and understand theory during lectures itself. After lectures, while studying, focus less on theory and more on problem solving.",
        "What is something you learned about internships, placements, projects or careers that you wish you knew earlier?": "The key to a great GPA is actually taking detailed notes during lectures. A LOT of problem solving later and intense revision.",
        "What is one thing you learned about friendships, people, failure, confidence, money or life?": "Everything fades with time, both failure and success, pain and happiness !",
        "What is one habit that genuinely changed you?": "Empathy",
        "Is there a book, person, quote, lecture, experience or idea that influenced you deeply?": "Learning how to fly by Abdul Kalam; The Guiding Light by Abdul Kalam",
        "Would you be open to helping juniors in the future?": "Yes",
        "What could juniors reach out to you about?": "About careers in core R&D Mechanical Engineering. GATE preparation (I cleared GATE with a good enough rank and post-graduated from IITD)",
        "LinkedIn / Email": "https://in.linkedin.com/in/mateen-mohsin-510945122",
        "Current country and company": "India and Danfoss"
    },
    {
        "Name": "Arbaaz Khan",
        "Batch / Graduation Year": "2021.0",
        "Branch": "Civil Engineering",
        "Can we mention your name when this is shared with juniors?": "Yes",
        "What is ONE thing you want to pass on to the juniors?": "Civil Engineering is the branch which has very very less job opportunities of all, as far as I know. I recommend Juniors to start upskilling yourself from 1st year itself, start finding out companies and see their job requirements, learn AutoCAD, Revit, Civil 3D, Synchro 4D, Primavera in the 1ST YEAR ITSELF ONLY as from 2nd year you won't get enough time for upskilling. Create a good CV and Portfolio in the 1st year, and by the end of Final year, you should have good CV and Portfolio when you're applying for jobs. Sit for the campus placement. Study the structural analysis, SFD, BMD well as it will be beneficial and will come to fruition even after college.\n\nRemember, these are the 'asbaab' which we have to use to reach to Allah s.w.t. Each and everything we do should be for the sake of Allah s.w.t even the job and the studies we're doing. Neglecting prayers and everything won't lead you nowhere even if you think you have achieved everything. There are numerous examples of the past where they achieved everything but didn't understand what Allah s.w.t wants from us, and their result is known to us.\n \"Then roam the Earth and see what became of the people who used to deny Our signs\".",
        "Was there a person, event, club, place or experience that made your college life special?": "Nope",
        "What is something at VNIT that you think juniors should experience at least once?": "Keeping away from haram, prayers on time.",
        "What is something you wish you had taken more seriously?": "Job hunting",
        "What is something you wish you had worried less about?": "Can't think of any rn.",
        "What is one decision you are really grateful you made during college?": "Nothing special, just grateful that I got this college.",
        "If you could go back to your first year, what would you do differently?": "Upskill myself.",
        "What is something you learned about internships, placements, projects or careers that you wish you knew earlier?": "Start it from the 1st year. Never ever ever ever ever depend on college. I mean, you should sit for placements and grab the best opportunity but what I mean is never be too negligent and just lean on college for placement.",
        "What is one resource that genuinely helped you?": "Seniors, studying in group with my batch mates.",
        "Is there an internship, interview, project or experience you think future batches would benefit from knowing about?": "I dont know of any.",
        "Any experience with any particular batch/senior that can resonate with upcoming batches.": "Not any.",
        "What is one thing VNIT taught you that had nothing to do with academics?": "Can't think of right now.",
        "What is one thing you learned about friendships, people, failure, confidence, money or life?": "People don't care about you, they're just a facade except genuine people",
        "What is one habit that genuinely changed you?": "Cant think of any",
        "What is something you understand today that you didn\u2019t understand when you entered VNIT?": "What do I say, job hunting.",
        "Would you be open to helping juniors in the future?": "Yes",
        "What could juniors reach out to you about?": "Career, Debates.",
        "Current country and company": "India, Precision Precast Solutions, Pvt. Ltd."
    },
    {
        "Name": "Shaik Nawaz Sharief",
        "Batch / Graduation Year": "2017.0",
        "Branch": "Chemical engineering",
        "Can we mention your name when this is shared with juniors?": "Yes",
        "What is ONE thing you want to pass on to the juniors?": "Never postpone the things to do on the last moments.",
        "Current country and company": "India, Magic Software"
    },
    {
        "Name": "Ahmed Mirza",
        "Batch / Graduation Year": "2019.0",
        "Branch": "Civil",
        "Can we mention your name when this is shared with juniors?": "Yes",
        "What is ONE thing you want to pass on to the juniors?": "Surround yourself with people who help you become a better human everyday. Spend time in understanding your strengths and weaknesses - this will help you get into the right rooms at the right time. Be honest with yourself. Dream bigger, stay humble and always remember Allah is the best of planners.",
        "Was there a person, event, club, place or experience that made your college life special?": "Axis and aarohi",
        "What is something at VNIT that you think juniors should experience at least once?": "Organizing event of any scale - that involves people and funds management",
        "What is something you wish you had taken more seriously?": "Working on a core skill consistently right from the 1st year",
        "What is one decision you are really grateful you made during college?": "Investing time in good friends",
        "If you could go back to your first year, what would you do differently?": "Spend 5% more time in learning 1 core skill consistently",
        "What is something you learned about internships, placements, projects or careers that you wish you knew earlier?": "Be genuinely curious and build a personality that people would enjoy working with and everything else will fall into place, just a matter of time",
        "What is one resource that genuinely helped you?": "Spending time with seniors and learning from them",
        "What is one thing VNIT taught you that had nothing to do with academics?": "Getting things done with the resources in hand",
        "What is one thing you learned about friendships, people, failure, confidence, money or life?": "Nothing is permanent otherwise and that's how it's meant to be. The quicker you learn and move on from failures is what will set up apart.",
        "What is one habit that genuinely changed you?": "Being self aware and accountable",
        "If juniors remember only ONE thing from you, what should it be?": "Never a stranger, here to help anytime!",
        "Would you be open to helping juniors in the future?": "Yes",
        "What could juniors reach out to you about?": "Interviews, higher ed, consulting, analytics, strategy, career guidance",
        "LinkedIn / Email": "linkedin.com/in/ahmedmirza37",
        "Current country and company": "Unilever, Bangalore, India"
    }
];
